---
- hosts: production
  become: true
  tasks:
  - name: Update PVE Script Repository
    ansible.builtin.shell: wget -4 https://raw.githubusercontent.com/solutions-hpe/pxmx-mgmt/main/clone.sh -O /etc/pve/scripts/clone.sh
  - name: Clone VMs
    ansible.builtin.shell: bash /etc/pve/scripts/clone.sh {{command}} {{start_vmid}} {{end_vmid}} {{vlan_id}} {{bridge_id}} {{sleep_time}} {{pool_id}} {{vm_name}} {{tpl_id}} {{smb_location}} {{shr_location}}