---
- name: Add Proxmox no-subscription repository
  hosts: proxmox_servers
  become: yes
  tasks:
  - name: Add no-subscription repository to sources list
    apt:
      name: "deb http://download.proxmox.com/debian {{ ansible_distribution_release }}/pve no-subscription"
      state: present
      file: /etc/apt/sources.list.d/pve-no-subscription.list
    
  - name: Update apt cache
    apt:
      update_cache: yes
