- name: Add Proxmox no-subscription repository
  hosts: production
  become: yes
  tasks:
  - name: Add no-subscription repository to sources list
    apt:
      name: "deb http://download.proxmox.com/debian bookworm pve-no-subscription"
      state: present
      file: /etc/apt/sources.list
    
  - name: Update apt cache
    apt:
      update_cache: yes
