--
- name: Check if Enterprise repo exists
  become: true
  ansible.builtin.stat:
    path=/etc/apt/sources.list.d/pve-enterprise.list
  register: pve_enterprise_repo

- name: Disable Enterprise Repo if enabled
  become: true
  when: pve_enterprise_repo.stat.exists
  command: mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.disabled

- name: Add the no-subscription repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ no_subscription_repo }}"
    filename: proxmox-no-subscription
    state: present
