---
- hosts: production
  become: true
  tasks:
  - name: Exit Maintenance Mode on Proxmox Cluster
    ansible.builtin.shell: wget -4 https://raw.githubusercontent.com/solutions-hpe/client-sim/main/clone.sh -O /etc/pve/scripts/clone.sh
